#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/herdstat/herdstat-action.
#
# SPDX-License-Identifier: MIT
#

name: 'Herdstat'
description: 'Analyze an open source project/community using the herdstat utility'
author: 'Sven Trieflinger'
branding:
  color: green
  icon: bar-chart
inputs:
  version:
    description: 'The herdstat CLI version to use'
    required: false
    default: "latest"
  configuration:
    description: 'The path to the herdstat configuration file'
    required: false
    default: ".herdstat.yaml"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.configuration }}
